import { test, expect } from '@playwright/test';
for (const width of [390, 1366]) {
  test(`copying a rule preserves settings and leaves the original unchanged at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    const original = { id: 'original', name: 'Banki kódok', senderType: 'specific', sender: 'BANK', keyword: '', keywords: 'OTP\nInfoCert', keywordMode: 'all', channel: 'email', targets: ['first@example.com', 'second@example.com'], target: 'first@example.com', enabled: false, sample: false };
    await page.evaluate(rule => localStorage.setItem('smsfwd.rules', JSON.stringify([rule])), original);
    await page.reload();
    await page.getByRole('button', { name: /^Banki kódok „/ }).click();
    await page.getByRole('button', { name: 'Szabály másolása', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Új továbbítási szabály' })).toBeVisible();
    await expect(page.getByRole('textbox', { name: 'Szabály neve' })).toHaveValue('Banki kódok – másolat');
    await expect(page.getByRole('textbox', { name: 'Feladó száma vagy neve' })).toHaveValue('BANK');
    await expect(page.getByRole('textbox', { name: 'Kulcsszavak' })).toHaveValue('OTP\nInfoCert');
    await expect(page.getByLabel('Szövegfeltétel')).toHaveValue('all');
    await expect(page.getByRole('textbox', { name: 'Címzett e-mail címe' })).toHaveValue('first@example.com\nsecond@example.com');
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('smsfwd.rules')))).toEqual([original]);
    await page.getByRole('button', { name: 'Mégse', exact: true }).click();
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('smsfwd.rules')))).toEqual([original]);
    await page.getByRole('button', { name: /^Banki kódok „/ }).click();
    await page.getByRole('button', { name: 'Szabály másolása', exact: true }).click();
    await page.getByRole('textbox', { name: 'Címzett e-mail címe' }).fill('third@example.com');
    await page.getByRole('button', { name: 'Szabály mentése' }).click();
    await page.reload();
    const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('smsfwd.rules')));
    expect(stored).toHaveLength(2);
    expect(stored[0]).toEqual(original);
    expect(stored[1].id).not.toBe(original.id);
    expect(stored[1]).toMatchObject({ name: 'Banki kódok – másolat', sender: 'BANK', keywords: 'OTP\nInfoCert', keywordMode: 'all', enabled: false, sample: false, target: 'third@example.com', targets: ['third@example.com'] });
    await page.getByRole('button', { name: /^Banki kódok – másolat „/ }).click();
    await expect(page.getByRole('textbox', { name: 'Címzett e-mail címe' })).toHaveValue('third@example.com');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  });
}
async function openTest(page) { await page.getByRole('button', { name: 'Beállítások', exact: true }).first().click(); await page.getByRole('button', { name: 'Szabály próba', exact: true }).click(); }

test('email settings explain the sender and do not store a password in the browser', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Beállítások', exact: true }).first().click();
  await page.getByRole('button', { name: 'Postafiók beállítása' }).click();
  await expect(page.getByRole('textbox', { name: 'SMTP-kiszolgáló' })).toHaveValue('smtp.gmail.com');
  await page.getByRole('textbox', { name: 'Küldő e-mail címe' }).fill('sender@example.com');
  await page.getByLabel('Alkalmazásjelszó', { exact: true }).fill('synthetic-test-only');
  await expect(page.getByLabel('Alkalmazásjelszó', { exact: true })).toHaveAttribute('type', 'password');
  await page.getByRole('button', { name: 'Jelszó megjelenítése' }).click();
  await expect(page.getByLabel('Alkalmazásjelszó', { exact: true })).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Jelszó elrejtése' }).click();
  await page.getByRole('button', { name: 'Postafiók mentése' }).click();
  await expect(page.getByRole('alert')).toContainText('Android-alkalmazásban');
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain('synthetic-test-only');
});
test('multiple recipients and keyword presets survive editing', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Próbáld ki' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Tesztüzenet indítása' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Új szabály', exact: true }).first().click();
  await page.getByRole('textbox', { name: 'Szabály neve' }).fill('Kódértesítések');
  await page.getByRole('button', { name: 'Jelszavas SMS-ek mintája' }).click();
  await page.getByRole('button', { name: 'Telefonszámra', exact: true }).click();
  await page.getByRole('textbox', { name: 'Címzett telefonszáma' }).fill('+36301112233\n+36302223344');
  await page.getByRole('button', { name: 'Szabály mentése' }).click();
  await expect(page.getByRole('button', { name: /Kódértesítések.*2 címzett/ })).toBeVisible();
  await page.getByRole('button', { name: 'Kódértesítések szerkesztése' }).click();
  await expect(page.getByRole('textbox', { name: 'Címzett telefonszáma' })).toHaveValue('+36301112233\n+36302223344');
  await page.keyboard.press('Escape');
  await openTest(page);
  await page.getByRole('textbox', { name: 'Üzenet szövege' }).fill('Az Ön egyszer használatos jelszava: 00000000');
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await expect(page.getByText('2 célra továbbítaná az alkalmazás.')).toBeVisible();
  await page.getByRole('textbox', { name: 'Üzenet szövege' }).fill('Szia, találkozunk holnap?');
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await expect(page.getByText('Egyetlen szabály sem illeszkedik.')).toBeVisible();
});

test('a saved rule persists and a matching simulation shows the destination', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Új szabály', exact: true }).first().click();
  await page.getByRole('textbox', { name: 'Szabály neve' }).fill('Csomagértesítés');
  await page.getByRole('textbox', { name: 'Kulcsszavak' }).fill('csomag');
  await page.getByRole('textbox', { name: 'Címzett e-mail címe' }).fill('teszt@example.com');
  await page.getByRole('button', { name: 'Szabály mentése' }).click();
  await expect(page.getByRole('button', { name: /Csomagértesítés MINTA/ })).toHaveCount(0);
  await expect(page.getByText('Csomagértesítés', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('Csomagértesítés', { exact: true })).toBeVisible();
  await openTest(page);
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await expect(page.getByRole('dialog').getByText('teszt@example.com', { exact: true })).toBeVisible();
  await expect(page.getByText('2 célra továbbítaná az alkalmazás.')).toBeVisible();
  await page.getByRole('button', { name: 'Bezárás', exact: true }).last().click();
  await page.getByRole('button', { name: 'Előzmények', exact: true }).first().click();
  await expect(page.getByText('Teszt sikeres')).toHaveCount(2);
  await page.getByRole('textbox', { name: 'Keresés az előzményekben' }).fill('teszt@example.com');
  await expect(page.getByText('Teszt sikeres')).toHaveCount(1);
});
test('pause blocks simulation and disabling a rule excludes it', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('switch', { name: 'Továbbítás bekapcsolása', exact: true }).click();
  await openTest(page);
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await expect(page.getByRole('dialog').getByText('A továbbítás szünetel.', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('switch', { name: 'Továbbítás bekapcsolása', exact: true }).click();
  await page.getByRole('button', { name: 'Áttekintés', exact: true }).first().click();
  await page.getByRole('switch', { name: 'Munkahelyi üzenetek szabály bekapcsolása' }).click();
  await openTest(page);
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await expect(page.getByText('Egyetlen szabály sem illeszkedik.')).toBeVisible();
});
test('a rule can be edited and deleted with confirmation', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Munkahelyi üzenetek szerkesztése' }).click();
  await page.getByRole('textbox', { name: 'Szabály neve' }).fill('Iroda');
  await page.getByRole('button', { name: 'Szabály mentése' }).click();
  await expect(page.getByText('Iroda', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Iroda szerkesztése' }).click();
  await page.getByRole('button', { name: 'Törlés', exact: true }).click();
  await page.getByRole('button', { name: 'Szabály törlése' }).click();
  await expect(page.getByText('Iroda', { exact: true })).toHaveCount(0);
});
test('invalid phone cannot be saved and SMS input is accepted in international format', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Új szabály', exact: true }).first().click();
  await page.getByRole('textbox', { name: 'Szabály neve' }).fill('Telefon');
  await page.getByRole('button', { name: 'Telefonszámra', exact: true }).click();
  await page.getByRole('textbox', { name: 'Címzett telefonszáma' }).fill('123');
  await page.getByRole('button', { name: 'Szabály mentése' }).click();
  await expect(page.getByRole('alert')).toContainText('országkóddal');
  await page.getByRole('textbox', { name: 'Címzett telefonszáma' }).fill('+36301112233');
  await page.getByRole('button', { name: 'Szabály mentése' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('Telefon', { exact: true })).toBeVisible();
});
test('mobile layout has no horizontal overflow and mobile navigation works', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('navigation', { name: 'Mobilmenü' }).getByRole('button', { name: 'Beállítások' }).click();
  await expect(page.getByRole('heading', { name: 'Eszköz és működés' })).toBeVisible();
  await page.getByRole('spinbutton', { name: 'Napi SMS szegmenslimit' }).fill('35');
  await page.reload();
  await page.getByRole('navigation', { name: 'Mobilmenü' }).getByRole('button', { name: 'Beállítások' }).click();
  await expect(page.getByRole('spinbutton', { name: 'Napi SMS szegmenslimit' })).toHaveValue('35');
});
test('history clear keeps the forwarding rules', async ({ page }) => {
  await page.goto('/');
  await openTest(page);
  await page.getByRole('button', { name: 'Teszt indítása', exact: true }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Előzmények', exact: true }).first().click();
  await page.getByRole('button', { name: 'Törlés', exact: true }).click();
  await page.getByRole('button', { name: 'Előzmények törlése' }).click();
  await expect(page.getByText('Nincs megjeleníthető esemény')).toBeVisible();
  await page.getByRole('button', { name: 'Szabályok', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Munkahelyi üzenetek szerkesztése' })).toBeVisible();
});
